// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHZltFwW8bSSTydhaPM1fD4G-6dbMJXrI',
    appId: '1:605214975464:web:fd23278b95907dd294305d',
    messagingSenderId: '605214975464',
    projectId: 'rolebased-b4aa9',
    authDomain: 'rolebased-b4aa9.firebaseapp.com',
    storageBucket: 'rolebased-b4aa9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTPFPCJMaGn2f49T39hQc41Gk1jcl_4lo',
    appId: '1:605214975464:android:9384cae35991c03594305d',
    messagingSenderId: '605214975464',
    projectId: 'rolebased-b4aa9',
    storageBucket: 'rolebased-b4aa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAHlPD2y_ahqwbAUxEsjz5C3GvvEPrsEA',
    appId: '1:605214975464:ios:fcaad1b164858c4694305d',
    messagingSenderId: '605214975464',
    projectId: 'rolebased-b4aa9',
    storageBucket: 'rolebased-b4aa9.appspot.com',
    iosClientId: '605214975464-m0tr8327nm9reds6caran95r1jaqkiau.apps.googleusercontent.com',
    iosBundleId: 'com.example.rolebased',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAHlPD2y_ahqwbAUxEsjz5C3GvvEPrsEA',
    appId: '1:605214975464:ios:fcaad1b164858c4694305d',
    messagingSenderId: '605214975464',
    projectId: 'rolebased-b4aa9',
    storageBucket: 'rolebased-b4aa9.appspot.com',
    iosClientId: '605214975464-m0tr8327nm9reds6caran95r1jaqkiau.apps.googleusercontent.com',
    iosBundleId: 'com.example.rolebased',
  );
}
